In [45]:
import numpy as np
x=np.array([1,2,3,5])  # 1-D Input Array as Input
N=int(input('Enter Number of Columns(greater than 0) needed in the Vandermonde Matrix: '))  # N is Number of columns in the output. If N is not specified, it will use default length of input array. N=len(x)
increasing=input('Enter True or False for increasing: ') #This is boolean input to determine the order of the powers of the column.

#if increasing is True -> the columns are x^0,x^1...x^N-1 (the powers increase from left to right)
## if increasing is False -> the columns are x^N-1,x^N-2...x^0 (the powers increase from right to left)

#method_program = int(input("Which method you want to use? Enter 1 -> VANDER METHOD; Enter 2 -> COLUMN STACK METHOD: "))


##Function 1 -> Matrix Generation using Vander method
def vander_method(x,N,increasing):
	if N==0 and increasing=='False':
		vandermonde_matrix=np.vander(x) # increasing is defaulted to "False"
	elif N==0 and increasing=='True':
		vandermonde_matrix=np.vander(x,increasing=True) 
	elif N>0 and increasing=='False':
		vandermonde_matrix=np.vander(x,N) #increasing is defaulted to "False"
	elif N>0 and increasing=='True':
		vandermonde_matrix=np.vander(x,N,increasing=True) 
		
	print('------------Vandermonde Matrix - Vandor Method ----------------')
	print(vandermonde_matrix)
		
	

##Function 2 -> Matrix Generation using Column Stack method
def col_stackmethod(x,N,increasing):     # Column Stack method 
	if N==0 and increasing=='False':
		vandermonde_matrix=np.column_stack([x**(N-i-1) for i in range(N)]) # increasing is defaulted to "False"
	elif N==0 and increasing=='True':
		vandermonde_matrix=np.column_stack([x**(N-i-1) for i in range(N-1,-1,-1)]) 
	elif N>0 and increasing=='False':
		vandermonde_matrix=np.column_stack([x**(N-i-1) for i in range(N)]) # increasing is defaulted to "False"
	elif N>0 and increasing=='True':
		vandermonde_matrix=np.column_stack([x**(N-i-1) for i in range(N-1,-1,-1)]) 
		
	print('-------------Vandermonde Matrix - Column Stack Method ----------------')
	print(vandermonde_matrix)
	

		
def main():       # Defining main function to call Vander_method or col_stackmethod function
    #if method_program == 1:
    vander_method(x,N,increasing)
    #else:
    col_stackmethod(x,N,increasing)

if __name__ == '__main__':      
	main()

------------Vandermonde Matrix - Vandor Method ----------------
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
-------------Vandermonde Matrix - Column Stack Method ----------------
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
